
CREATE TABLE PRESENTATION_TEMPLATE (
                PRESENTATION_TEMPLATE_ID IDENTITY NOT NULL,
                PRESENTATION_TEMPLATE_NAME VARCHAR(60) NOT NULL,
                CONSTRAINT PK_PRESENTATION_TEMPLATE PRIMARY KEY (PRESENTATION_TEMPLATE_ID)
);


CREATE TABLE SLIDE (
                SLIDE_ID IDENTITY NOT NULL,
                SLIDE_TITLE VARCHAR(60) NOT NULL,
                SLIDE_META VARCHAR(2048),
                CONSTRAINT PK_SLIDE PRIMARY KEY (SLIDE_ID)
);


CREATE TABLE PRESENTATION_TEMPLATE_SLIDE (
                PRESENTATION_TEMPLATE_SLIDE_ID IDENTITY NOT NULL,
                PRESENTATION_TEMPLATE_SLIDE_POSITION INTEGER NOT NULL,
                PRESENTATION_TEMPLATE_ID INTEGER NOT NULL,
                SLIDE_ID INTEGER NOT NULL,
                CONSTRAINT PK_PRESENTATION_TEMPLATE_SLIDE PRIMARY KEY (PRESENTATION_TEMPLATE_SLIDE_ID)
);


CREATE TABLE SLIDE_DATA_TYPE (
                SLIDE_DATA_TYPE_ID IDENTITY NOT NULL,
                SLIDE_TYPE_NAME VARCHAR(60) NOT NULL,
                CONSTRAINT PK_SLIDE_DATA_TYPE PRIMARY KEY (SLIDE_DATA_TYPE_ID)
);


CREATE TABLE SLIDE_DATA (
                SLIDE_DATA_ID IDENTITY NOT NULL,
                SLIDE_DATA_TEXT VARCHAR(8192),
                SLIDE_DATA_BINARY BINARY,
                SLIDE_DATA_TYPE_ID INTEGER NOT NULL,
                CONSTRAINT PK_SLIDE_DATA PRIMARY KEY (SLIDE_DATA_ID)
);


CREATE TABLE SLIDE_SLIDEDATA (
                SLIDE_SLIDEDATA_ID IDENTITY NOT NULL,
                SLIDE_DATA_ID INTEGER NOT NULL,
                SLIDE_ID INTEGER NOT NULL,
                CONSTRAINT PK_SLIDE_SLIDEDATA PRIMARY KEY (SLIDE_SLIDEDATA_ID)
);


CREATE TABLE USER_GROUP (
                USER_GROUP_ID IDENTITY NOT NULL,
                USER_GROUP_NAME VARCHAR(60) NOT NULL,
                CONSTRAINT PK_USER_GROUP PRIMARY KEY (USER_GROUP_ID)
);


CREATE TABLE PRESENTATION (
                PRESENTATION_ID IDENTITY NOT NULL,
                PRESENTATION_DATE DATE NOT NULL,
                USER_GROUP_ID INTEGER NOT NULL,
                CONSTRAINT PK_PRESENTATION PRIMARY KEY (PRESENTATION_ID)
);


CREATE TABLE PRESENTATION_SLIDES (
                PRESENTATION_SLIDES_ID IDENTITY NOT NULL,
                PRESENTATION_SLIDES_POSITION INTEGER NOT NULL,
                PRESENTATION_TEMPLATE_ID INTEGER NOT NULL,
                PRESENTATION_ID INTEGER NOT NULL,
                SLIDE_ID INTEGER NOT NULL,
                CONSTRAINT PK_PRESENTATION_SLIDES PRIMARY KEY (PRESENTATION_SLIDES_ID)
);


CREATE INDEX SERVICE_TEMP_SERV_ORDER_FK1
 ON PRESENTATION_SLIDES
 ( PRESENTATION_TEMPLATE_ID ASC );

ALTER TABLE PRESENTATION_SLIDES ADD CONSTRAINT PRESENTATION_TEMPLATE_PRESENTATION_SLIDES_fk
FOREIGN KEY (PRESENTATION_TEMPLATE_ID)
REFERENCES PRESENTATION_TEMPLATE (PRESENTATION_TEMPLATE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESENTATION_TEMPLATE_SLIDE ADD CONSTRAINT PRESENTATION_TEMPLATE_PRESENTATION_TEMPLATE_SLIDE_fk
FOREIGN KEY (PRESENTATION_TEMPLATE_ID)
REFERENCES PRESENTATION_TEMPLATE (PRESENTATION_TEMPLATE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SLIDE_SLIDEDATA ADD CONSTRAINT SLIDE_SLIDE_SLIDEDATA_fk
FOREIGN KEY (SLIDE_ID)
REFERENCES SLIDE (SLIDE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESENTATION_SLIDES ADD CONSTRAINT SLIDE_PRESENTATION_SLIDES_fk
FOREIGN KEY (SLIDE_ID)
REFERENCES SLIDE (SLIDE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESENTATION_TEMPLATE_SLIDE ADD CONSTRAINT SLIDE_PRESENTATION_TEMPLATE_SLIDE_fk
FOREIGN KEY (SLIDE_ID)
REFERENCES SLIDE (SLIDE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SLIDE_DATA ADD CONSTRAINT SLIDE_TYPE_SLIDE_DATA_fk
FOREIGN KEY (SLIDE_DATA_TYPE_ID)
REFERENCES SLIDE_DATA_TYPE (SLIDE_DATA_TYPE_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE SLIDE_SLIDEDATA ADD CONSTRAINT SLIDE_DATA_SLIDE_SLIDEDATA_fk
FOREIGN KEY (SLIDE_DATA_ID)
REFERENCES SLIDE_DATA (SLIDE_DATA_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESENTATION ADD CONSTRAINT USER_GROUP_SERVICE_fk
FOREIGN KEY (USER_GROUP_ID)
REFERENCES USER_GROUP (USER_GROUP_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PRESENTATION_SLIDES ADD CONSTRAINT PRESENTATION_SERVICE_ORDER_fk
FOREIGN KEY (PRESENTATION_ID)
REFERENCES PRESENTATION (PRESENTATION_ID)
ON DELETE NO ACTION
ON UPDATE NO ACTION;